
name: Deploy Location Services to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

      - name: Deploy Application
        run: |
          echo "EC2 Instance started. Deploying application..."

  call-deploy-to-aws:
    needs: deploy  # Ensures EC2 starts before deployment
    uses: Tecvinson-AB/realestate-iac/.github/workflows/realestate_reusable.yaml@main  
    with:
      app_name: "location-services"
      docker_build_dir: .
      spring_profile: production

    secrets:
      EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ secrets.AWS_REGION }}
      ec2_user: ${{ secrets.EC2_USER }}
      ec2_host: ${{ secrets.EC2_HOST }}
      ec2_ssh_key: ${{ secrets.EC2_SSH_KEY }}
      ecr_registry: ${{ secrets.ECR_REGISTRY }}
      mysql_connection_string: ${{ secrets.MYSQL_CONNECTION_STRING }}
      db_user: ${{ secrets.DB_USER }}
      db_password: ${{ secrets.DB_PASSWORD }}
